# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/izael/Documents/git/RVWeb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/izael/Documents/git/RVWeb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/izael/Documents/git/RVWeb/CMakeFiles /home/izael/Documents/git/RVWeb//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/izael/Documents/git/RVWeb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rvweb

# Build rule for target.
rvweb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rvweb
.PHONY : rvweb

# fast build rule for target.
rvweb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/build
.PHONY : rvweb/fast

src/CSVParser.o: src/CSVParser.cpp.o
.PHONY : src/CSVParser.o

# target to build an object file
src/CSVParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/CSVParser.cpp.o
.PHONY : src/CSVParser.cpp.o

src/CSVParser.i: src/CSVParser.cpp.i
.PHONY : src/CSVParser.i

# target to preprocess a source file
src/CSVParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/CSVParser.cpp.i
.PHONY : src/CSVParser.cpp.i

src/CSVParser.s: src/CSVParser.cpp.s
.PHONY : src/CSVParser.s

# target to generate assembly for a file
src/CSVParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/CSVParser.cpp.s
.PHONY : src/CSVParser.cpp.s

src/Clustering.o: src/Clustering.cpp.o
.PHONY : src/Clustering.o

# target to build an object file
src/Clustering.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Clustering.cpp.o
.PHONY : src/Clustering.cpp.o

src/Clustering.i: src/Clustering.cpp.i
.PHONY : src/Clustering.i

# target to preprocess a source file
src/Clustering.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Clustering.cpp.i
.PHONY : src/Clustering.cpp.i

src/Clustering.s: src/Clustering.cpp.s
.PHONY : src/Clustering.s

# target to generate assembly for a file
src/Clustering.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Clustering.cpp.s
.PHONY : src/Clustering.cpp.s

src/IJKKey.o: src/IJKKey.cpp.o
.PHONY : src/IJKKey.o

# target to build an object file
src/IJKKey.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/IJKKey.cpp.o
.PHONY : src/IJKKey.cpp.o

src/IJKKey.i: src/IJKKey.cpp.i
.PHONY : src/IJKKey.i

# target to preprocess a source file
src/IJKKey.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/IJKKey.cpp.i
.PHONY : src/IJKKey.cpp.i

src/IJKKey.s: src/IJKKey.cpp.s
.PHONY : src/IJKKey.s

# target to generate assembly for a file
src/IJKKey.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/IJKKey.cpp.s
.PHONY : src/IJKKey.cpp.s

src/Metadata.o: src/Metadata.cpp.o
.PHONY : src/Metadata.o

# target to build an object file
src/Metadata.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Metadata.cpp.o
.PHONY : src/Metadata.cpp.o

src/Metadata.i: src/Metadata.cpp.i
.PHONY : src/Metadata.i

# target to preprocess a source file
src/Metadata.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Metadata.cpp.i
.PHONY : src/Metadata.cpp.i

src/Metadata.s: src/Metadata.cpp.s
.PHONY : src/Metadata.s

# target to generate assembly for a file
src/Metadata.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Metadata.cpp.s
.PHONY : src/Metadata.cpp.s

src/Pixelization.o: src/Pixelization.cpp.o
.PHONY : src/Pixelization.o

# target to build an object file
src/Pixelization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Pixelization.cpp.o
.PHONY : src/Pixelization.cpp.o

src/Pixelization.i: src/Pixelization.cpp.i
.PHONY : src/Pixelization.i

# target to preprocess a source file
src/Pixelization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Pixelization.cpp.i
.PHONY : src/Pixelization.cpp.i

src/Pixelization.s: src/Pixelization.cpp.s
.PHONY : src/Pixelization.s

# target to generate assembly for a file
src/Pixelization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Pixelization.cpp.s
.PHONY : src/Pixelization.cpp.s

src/Property.o: src/Property.cpp.o
.PHONY : src/Property.o

# target to build an object file
src/Property.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Property.cpp.o
.PHONY : src/Property.cpp.o

src/Property.i: src/Property.cpp.i
.PHONY : src/Property.i

# target to preprocess a source file
src/Property.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Property.cpp.i
.PHONY : src/Property.cpp.i

src/Property.s: src/Property.cpp.s
.PHONY : src/Property.s

# target to generate assembly for a file
src/Property.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Property.cpp.s
.PHONY : src/Property.cpp.s

src/SnakeCurve.o: src/SnakeCurve.cpp.o
.PHONY : src/SnakeCurve.o

# target to build an object file
src/SnakeCurve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/SnakeCurve.cpp.o
.PHONY : src/SnakeCurve.cpp.o

src/SnakeCurve.i: src/SnakeCurve.cpp.i
.PHONY : src/SnakeCurve.i

# target to preprocess a source file
src/SnakeCurve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/SnakeCurve.cpp.i
.PHONY : src/SnakeCurve.cpp.i

src/SnakeCurve.s: src/SnakeCurve.cpp.s
.PHONY : src/SnakeCurve.s

# target to generate assembly for a file
src/SnakeCurve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/SnakeCurve.cpp.s
.PHONY : src/SnakeCurve.cpp.s

src/Strategy.o: src/Strategy.cpp.o
.PHONY : src/Strategy.o

# target to build an object file
src/Strategy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Strategy.cpp.o
.PHONY : src/Strategy.cpp.o

src/Strategy.i: src/Strategy.cpp.i
.PHONY : src/Strategy.i

# target to preprocess a source file
src/Strategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Strategy.cpp.i
.PHONY : src/Strategy.cpp.i

src/Strategy.s: src/Strategy.cpp.s
.PHONY : src/Strategy.s

# target to generate assembly for a file
src/Strategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/Strategy.cpp.s
.PHONY : src/Strategy.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rvweb.dir/build.make CMakeFiles/rvweb.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rvweb"
	@echo "... src/CSVParser.o"
	@echo "... src/CSVParser.i"
	@echo "... src/CSVParser.s"
	@echo "... src/Clustering.o"
	@echo "... src/Clustering.i"
	@echo "... src/Clustering.s"
	@echo "... src/IJKKey.o"
	@echo "... src/IJKKey.i"
	@echo "... src/IJKKey.s"
	@echo "... src/Metadata.o"
	@echo "... src/Metadata.i"
	@echo "... src/Metadata.s"
	@echo "... src/Pixelization.o"
	@echo "... src/Pixelization.i"
	@echo "... src/Pixelization.s"
	@echo "... src/Property.o"
	@echo "... src/Property.i"
	@echo "... src/Property.s"
	@echo "... src/SnakeCurve.o"
	@echo "... src/SnakeCurve.i"
	@echo "... src/SnakeCurve.s"
	@echo "... src/Strategy.o"
	@echo "... src/Strategy.i"
	@echo "... src/Strategy.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

