# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\k\Documents\Unicamp\IC\ReservoirViewerWeb\RVWeb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\k\Documents\Unicamp\IC\ReservoirViewerWeb\RVWeb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\k\Documents\Unicamp\IC\ReservoirViewerWeb\RVWeb\CMakeFiles C:\Users\k\Documents\Unicamp\IC\ReservoirViewerWeb\RVWeb\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\k\Documents\Unicamp\IC\ReservoirViewerWeb\RVWeb\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RVWeb

# Build rule for target.
RVWeb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 RVWeb
.PHONY : RVWeb

# fast build rule for target.
RVWeb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RVWeb.dir\build.make CMakeFiles/RVWeb.dir/build
.PHONY : RVWeb/fast

src/Property.obj: src/Property.cpp.obj
.PHONY : src/Property.obj

# target to build an object file
src/Property.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RVWeb.dir\build.make CMakeFiles/RVWeb.dir/src/Property.cpp.obj
.PHONY : src/Property.cpp.obj

src/Property.i: src/Property.cpp.i
.PHONY : src/Property.i

# target to preprocess a source file
src/Property.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RVWeb.dir\build.make CMakeFiles/RVWeb.dir/src/Property.cpp.i
.PHONY : src/Property.cpp.i

src/Property.s: src/Property.cpp.s
.PHONY : src/Property.s

# target to generate assembly for a file
src/Property.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RVWeb.dir\build.make CMakeFiles/RVWeb.dir/src/Property.cpp.s
.PHONY : src/Property.cpp.s

src/RVConfig.obj: src/RVConfig.cpp.obj
.PHONY : src/RVConfig.obj

# target to build an object file
src/RVConfig.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RVWeb.dir\build.make CMakeFiles/RVWeb.dir/src/RVConfig.cpp.obj
.PHONY : src/RVConfig.cpp.obj

src/RVConfig.i: src/RVConfig.cpp.i
.PHONY : src/RVConfig.i

# target to preprocess a source file
src/RVConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RVWeb.dir\build.make CMakeFiles/RVWeb.dir/src/RVConfig.cpp.i
.PHONY : src/RVConfig.cpp.i

src/RVConfig.s: src/RVConfig.cpp.s
.PHONY : src/RVConfig.s

# target to generate assembly for a file
src/RVConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RVWeb.dir\build.make CMakeFiles/RVWeb.dir/src/RVConfig.cpp.s
.PHONY : src/RVConfig.cpp.s

src/Strategy.obj: src/Strategy.cpp.obj
.PHONY : src/Strategy.obj

# target to build an object file
src/Strategy.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RVWeb.dir\build.make CMakeFiles/RVWeb.dir/src/Strategy.cpp.obj
.PHONY : src/Strategy.cpp.obj

src/Strategy.i: src/Strategy.cpp.i
.PHONY : src/Strategy.i

# target to preprocess a source file
src/Strategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RVWeb.dir\build.make CMakeFiles/RVWeb.dir/src/Strategy.cpp.i
.PHONY : src/Strategy.cpp.i

src/Strategy.s: src/Strategy.cpp.s
.PHONY : src/Strategy.s

# target to generate assembly for a file
src/Strategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RVWeb.dir\build.make CMakeFiles/RVWeb.dir/src/Strategy.cpp.s
.PHONY : src/Strategy.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RVWeb.dir\build.make CMakeFiles/RVWeb.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RVWeb.dir\build.make CMakeFiles/RVWeb.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RVWeb.dir\build.make CMakeFiles/RVWeb.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... RVWeb
	@echo ... src/Property.obj
	@echo ... src/Property.i
	@echo ... src/Property.s
	@echo ... src/RVConfig.obj
	@echo ... src/RVConfig.i
	@echo ... src/RVConfig.s
	@echo ... src/Strategy.obj
	@echo ... src/Strategy.i
	@echo ... src/Strategy.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

